djangopractice/Mysite/Mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),

]

djangopractice/Mysite/food/urls.py
from django.urls import path
from . import views

app_name = "food"
urlpatterns = [
    # food
    path('', views.index, name='index'),
    # food/1
    path('<int:item_id>/', views.detail, name='detail'),
    path('item/', views.item, name='item'),
    # add item
    path('add/', views.create_item, name='create_item'),
    # edit item
    path('update/<int:item_id>/', views.update_item, name='update_item'),
    # delete item
    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),
]

djangopractice/Mysite/food/models.py
from django.db import models

# Create your models here.


class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500, default="https://th.bing.com/th/id/R.861d624cb303db96322dcaeb6ed99e9b?rik=CstlEO2%2fm6Xy4w&riu=http%3a%2f%2fthefooddisciple.com%2fwp-content%2fuploads%2f2015%2f09%2fneptune-placeholder-40.jpg&ehk=oOphLDO0j3MFugqqnhbpZY5C1OyvfNcEvqRdyVpkIzk%3d&risl=&pid=ImgRaw&r=0")

djangopractice/Mysite/users/models.py
from django.db import models

# Create your models here.

djangopractice/Mysite/food/forms.py
from django import forms
from . models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

djangopractice/Mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

djangopractice/Mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from . models import Item
from django.template import loader
from . forms import ItemForm
# Create your views here.


def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'food/index.html', context)


def item(request):
    return HttpResponse("<h1>Item View</h1>")


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item
    }
    # return ("This is item id no: %s" % item_id)
    # return HttpResponse(f"This is item Id no: {item_id}")
    return render(request, 'food/detail.html', context)


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})


def update_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form, 'item': item})


def delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html', {'item': item})

djangopractice/Mysite/users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f"Welcome {username}, your account is created!")
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

djangopractice/Mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>FoodApp</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark" style="padding: 15px;">
        <a href=" #" class=" navbar-brand"> FoodApp</a>

        <div class="navbar">
            <a class="nav-item link-primary m-2" href="{% url 'food:create_item' %}"> Add Item</a>
            <a class="nav-item link-primary m-2" href="#"> View Item</a>
            <a class="nav-item link-primary m-2" href="#"> Delete Item</a>
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' % }">logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </div>
    </nav>
    <!-- writing success response here -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags}}">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    <!-- code starts in block body and ends in endblock -->

    {% block body %}
    {% endblock %}
</body>

</html>

djangopractice/Mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
<!-- <h1>{{item.item_name}}</h1>
<h2>{{item.item_desc}}</h2>
<h3>{{item.item_price}}</h3> -->
{% block body %}

<div class="container">
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6">
            <img height=400px width=400px src="{{ item.item_image }}" class="card" />
        </div>
        <div class="col-md-6" style="margin: auto;">
            <h2>{{item.item_name}}</h2>
            <h2>{{item.item_desc}}</h2>
            <h2>{{item.item_price}}</h2>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

<!-- ItemName : {{item.item_name}}
ItemDesc : {{item.item_desc}}
Itemprice : {{item.item_price}} -->

djangopractice/Mysite/food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    {% block body %}

    {% for item in item_list %}
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="180px" width="180px" src="{{ item.item_image }}">
        </div>

        <div class="col-md-3">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>{{item.item_price}}</h6>
        </div>
        <div class="col-md-1">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success" style="margin-top: 30px;">Details</a>
        </div>
        <!-- hr is used to add line between each data. -->
        <hr style="margin-top: 20px;" />

    </div>

    <!-- <ul>
        <li>
            <!-- {{item.id}} -- {{ item.item_name }} -->
    <!-- <a href="/food/{{item.id}}">{{item.id}} -- {{ item.item_name }}</a> -->
    <!-- <a href="{% url 'food:detail' item.id %}">{{item.id}} -- {{ item.item_name }}</a>
        </li>
    </ul> --> -->
    {% endfor %}

    {% endblock %}
</body>

</html>

djangopractice/Mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST" style="padding-left: 10px;">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

djangopractice/Mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST" style="margin-top: 20px;">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SAVE</button>
</form>
{% endblock %}

djangopractice/Mysite/users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

djangopractice/Mysite/users/templates/users/logout.html
<h1>You have been Logged out</h1>

djangopractice/Mysite/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" style="background-color: lightblue; margin: auto;">SignUp</button>
</form>